# Generated by Django 3.1.4 on 2020-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_reg_tb',
            name='proof',
            field=models.FileField(default='No proof', upload_to=''),
        ),
    ]
