# Generated by Django 3.1.4 on 2020-12-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_owner_reg_tb_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='fisher_boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('regno', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='')),
                ('no_of_empl', models.CharField(max_length=20)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.owner_reg_tb')),
            ],
        ),
    ]
