# Generated by Django 3.1.4 on 2020-12-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_fisher_boat'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_reg_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('dob', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
