# Generated by Django 3.1.4 on 2020-12-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0004_employee_reg_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_reg_tb',
            name='boat_id',
            field=models.CharField(default='No id', max_length=20),
        ),
        migrations.AddField(
            model_name='employee_reg_tb',
            name='boat_name',
            field=models.CharField(default='No name', max_length=20),
        ),
    ]
