# Generated by Django 3.1.4 on 2021-01-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0005_auto_20201231_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_reg_tb',
            name='boat_name',
        ),
        migrations.RemoveField(
            model_name='employee_reg_tb',
            name='status',
        ),
        migrations.AlterField(
            model_name='employee_reg_tb',
            name='boat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.fisher_boat'),
        ),
    ]
