# Generated by Django 3.1.4 on 2021-01-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0008_employee_reg_tb_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_reg_tb',
            name='owner_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Owner.owner_reg_tb'),
        ),
    ]
