# Generated by Django 3.1.4 on 2021-01-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0009_auto_20210109_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_reg_tb',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Owner.owner_reg_tb'),
        ),
    ]
