# Generated by Django 3.1.4 on 2021-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0013_auto_20210116_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisher_fish',
            name='date',
            field=models.CharField(default='No date', max_length=10),
        ),
        migrations.AddField(
            model_name='fisher_fish',
            name='end_time',
            field=models.CharField(default='No time', max_length=20),
        ),
        migrations.AddField(
            model_name='fisher_fish',
            name='start_time',
            field=models.CharField(default='No time', max_length=20),
        ),
        migrations.AddField(
            model_name='fisher_fish',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
