# Generated by Django 3.1.4 on 2021-01-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0014_auto_20210116_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisher_fish',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
