# Generated by Django 3.1.4 on 2021-02-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0015_auto_20210130_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisher_boat',
            name='no_of_empl',
            field=models.IntegerField(),
        ),
    ]
