# Generated by Django 3.1.4 on 2021-01-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_reg_tb')),
            ],
        ),
    ]
