# Generated by Django 3.1.4 on 2021-02-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0015_auto_20210130_0721'),
        ('Customer', '0002_auction_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_reg_tb')),
                ('fish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.fisher_fish')),
            ],
        ),
    ]
