# Generated by Django 3.1.4 on 2021-02-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_bidding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auction_tb',
        ),
    ]
