# Generated by Django 3.1.4 on 2021-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_delete_auction_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='status',
            field=models.CharField(default='Ongoing', max_length=20),
        ),
    ]
