# Generated by Django 3.1.4 on 2021-03-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_complaint_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_tb',
            name='cust_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_reg_tb'),
        ),
    ]
