# Generated by Django 3.1.4 on 2021-03-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_complaint_tb_cust_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('compl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.complaint_tb')),
            ],
        ),
    ]
