# Generated by Django 3.1.1 on 2021-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_reply_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
