# Generated by Django 3.1.1 on 2021-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_auto_20210328_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_tb',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
