# Generated by Django 3.1.4 on 2021-02-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0016_auto_20210227_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('empl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.employee_reg_tb')),
            ],
        ),
    ]
