# Generated by Django 3.1.1 on 2021-04-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_tb',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
